theme = "plain"
icons = "awesome"


[[block]]
block = "disk_space"
path = "/"
alias = "root"
info_type = "available"
unit = "GB"
interval = 120

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 120

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 20

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "pacman"
interval = 1800

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
